name: Deploy to AWS EKS

on:
  push:
    branches: 
      - main
env:
  ECR_REPOSITORY: sca_project
  CLUSTER_NAME: actions-demo
  REGION: us-east-1
  ECR_REGISTRY: public.ecr.aws/g8t1g9i0/sca_project
  IMAGE_TAG: latest


jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.3'
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAQ4P4MSRP5DR3PCF7
        aws-secret-access-key: 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
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} 

      run: |
        docker build -t g8t1g9i0/sca_project:latest .
        docker push $g8t1g9i0/sca_project:latestG
    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Update kube config
      run: aws eks update-kubeconfig --name $CLUSTER_NAME --region $REGION  


    - name: Deploy
      run: |-
        # replacing the image name in the k8s template
        ./kustomize edit set image image-name=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services 
